# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 650b91439a452b216d2a81a23e9634e6a5b38787419177df362e8ab8c83c40b62cee31ec7b3bd07d0c3ea46082aa031b2e3cd702d2e4a2e10462a91d93e54873

test:
  secret_key_base: 96ea3c7cf69aa1f41ed57b2f5614e30ef0de94b89a6b60c015e2f1bb68c422799d463e3b4b3ec4049d3848340ecc9230558b1f589d57d2fa31be29fb158a5377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
